stages:
  download-adult-dataset:
    cmd: skidless run-download-adult-dataset
    deps:
    - skidless/datasets.py
    outs:
    - data/bronze/adult.data.csv
    - data/bronze/adult.test.csv
  clean-adult-dataset:
    cmd: skidless run-clean-adult-dataset
    deps:
    - skidless/cleaning.py
    - data/bronze/adult.data.csv
    - data/bronze/adult.test.csv
    outs:
    - data/silver/adult.data.parquet
    - data/silver/adult.test.parquet
  train-preprocessors-and-featurize-adult-dataset:
    cmd: skidless run-train-preprocessors-and-featurize-train-adult-dataset
    deps:
    - skidless/features.py
    - data/silver/adult.data.parquet
    outs:
    - data/gold/adult.data.parquet
    - models/feature-preprocessor
    - models/target-preprocessor
