stages:
  download-adult-dataset:
    cmd: skidless run-download-adult-dataset
    deps:
    - skidless/datasets.py
    outs:
    - data/bronze/adult.data.csv
    - data/bronze/adult.test.csv
  clean-adult-dataset:
    cmd: skidless run-clean-adult-dataset
    deps:
    - skidless/cleaning.py
    - data/bronze/adult.data.csv
    - data/bronze/adult.test.csv
    params:
    - clean.raw_columns
    - features.target_name
    - features.numerical_features
    - features.categorical_features
    outs:
    - data/silver/adult.data.parquet
    - data/silver/adult.test.parquet
  train-preprocessors-and-featurize-train-adult-dataset:
    cmd: skidless run-train-preprocessors-and-featurize-train-adult-dataset
    deps:
    - skidless/features.py
    - data/silver/adult.data.parquet
    params:
    - features.target_name
    - features.numerical_features
    - features.categorical_features
    outs:
    - data/gold/adult.data.parquet
    - models/feature-preprocessor
    - models/target-preprocessor
  train-model:
    cmd: skidless run-train-model
    deps:
    - skidless/model.py
    - data/gold/adult.data.parquet
    params:
    - features.target_name
    - features.numerical_features
    - features.categorical_features
    - model.learning_rate
    - model.max_depth
    - model.n_estimators
    - model.n_jobs
    - model.random_state
    outs:
    - models/model
